In [1]:
import pandas as pd
import researchpy as rp

ModuleNotFoundError: No module named 'researchpy'

In [2]:
pip install researchpy

Collecting researchpy
  Downloading researchpy-0.3.2-py3-none-any.whl (15 kB)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (from researchpy) (1.18.5)
Requirement already satisfied: scipy in c:\users\hp\anaconda3\lib\site-packages (from researchpy) (1.7.1)
Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (from researchpy) (1.3.4)
Requirement already satisfied: statsmodels in c:\users\hp\anaconda3\lib\site-packages (from researchpy) (0.12.2)
Requirement already satisfied: patsy in c:\users\hp\anaconda3\lib\site-packages (from researchpy) (0.5.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\hp\anaconda3\lib\site-packages (from pandas->researchpy) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\hp\anaconda3\lib\site-packages (from pandas->researchpy) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->researchpy) (1.15.0)
Installing collected packages: researchpy
Successfully installed researchpy-0.3.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import researchpy as rp

In [2]:
data = pd.read_csv("C:/Users/HP/Documents/BDMDM/NIke_Dataset.csv")

In [3]:
data.head()

,Customer_number,usage,sex,awareness,attitude,preference,intention,loyalty,income
0,1,Heavy,Male,7.0,6.0,5.0,5.0,6.0,95000
1,2,Light,Female,2.0,2.0,4.0,6.0,5.0,60890
2,3,Light,Female,3.0,3.0,6.0,7.0,6.0,50998
3,4,Heavy,Male,6.0,5.0,5.0,3.0,2.0,79103
4,5,Heavy,Male,5.0,4.0,7.0,4.0,3.0,74216

In [4]:
data

,Customer_number,usage,sex,awareness,attitude,preference,intention,loyalty,income
0,1,Heavy,Male,7.0,6.0,5.0,5.0,6.0,95000
1,2,Light,Female,2.0,2.0,4.0,6.0,5.0,60890
2,3,Light,Female,3.0,3.0,6.0,7.0,6.0,50998
3,4,Heavy,Male,6.0,5.0,5.0,3.0,2.0,79103
4,5,Heavy,Male,5.0,4.0,7.0,4.0,3.0,74216
5,6,Medium,Male,4.0,3.0,5.0,2.0,3.0,31058
6,7,Medium,Female,5.0,4.0,4.0,3.0,2.0,24291
7,8,Light,Female,2.0,1.0,3.0,4.0,5.0,56189
8,9,Medium,Male,4.0,4.0,3.0,6.0,5.0,31860
9,10,Light,Female,3.0,1.0,2.0,4.0,5.0,56075
10,11,Heavy,Male,6.0,7.0,6.0,4.0,5.0,77951
11,12,Heavy,Male,6.0,5.0,6.0,4.0,4.0,78718
12,13,Light,Female,4.0,3.0,3.0,1.0,1.0,51668
13,14,Heavy,Male,6.0,4.0,5.0,3.0,2.0,55936
14,15,Light,Male,4.0,3.0,4.0,5.0,6.0,56309
15,16,Light,Male,3.0,4.0,2.0,4.0,2.0,54319
16,17,Heavy,Female,7.0,6.0,4.0,5.0,3.0,70087
17,18,Medium,Female,6.0,5.0,4.0,3.0,2.0,37434
18,19,Light,Female,1.0,1.0,3.0,4.0,5.0,59689
19,20,Heavy,Female,5.0,7.0,4.0,1.0,2.0,65861
20,21,Heavy,Male,6.0,6.0,7.0,7.0,5.0,72828
21,22,Medium,Male,2.0,3.0,1.0,4.0,2.0,42000
22,23,Light,Female,1.0,1.0,3.0,2.0,2.0,55523
23,24,Heavy,Female,6.0,7.0,6.0,7.0,6.0,78178
24,25,Light,Male,3.0,2.0,2.0,1.0,1.0,53595
25,26,Medium,Male,5.0,3.0,4.0,4.0,5.0,35558
26,27,Heavy,Male,7.0,6.0,6.0,5.0,7.0,84357
27,28,Medium,Female,6.0,4.0,2.0,5.0,6.0,30420
28,29,Light,Female,NaN,2.0,3.0,1.0,3.0,52787
29,30,Medium,Male,5.0,NaN,4.0,6.0,5.0,41000
30,31,Light,Male,1.0,2.0,NaN,3.0,2.0,72000
31,32,Light,Male,4.0,6.0,5.0,NaN,3.0,63882
32,33,Medium,Female,3.0,4.0,3.0,2.0,NaN,31104
33,34,Medium,Female,4.0,6.0,5.0,7.0,6.0,43000
34,35,Heavy,Female,5.0,7.0,7.0,3.0,3.0,75081
35,36,Heavy,Female,6.0,5.0,7.0,3.0,4.0,71775
36,37,Heavy,Male,6.0,7.0,5.0,3.0,4.0,73620
37,38,Heavy,Male,5.0,6.0,4.0,3.0,2.0,66291
38,39,Heavy,Male,7.0,7.0,6.0,3.0,4.0,63410
39,40,Light,Female,4.0,3.0,4.0,6.0,5.0,55116
40,41,Light,Female,2.0,3.0,4.0,5.0,6.0,65680
41,42,Light,Female,1.0,3.0,2.0,3.0,4.0,47713
42,43,Light,Female,2.0,4.0,3.0,6.0,7.0,50896
43,44,Light,Female,3.0,3.0,4.0,6.0,5.0,63848
44,45,Light,Female,1.0,1.0,4.0,5.0,3.0,52704

In [5]:
### replacing values of other attributes by group mean\n",
data['awareness'].fillna(data.groupby(['usage','sex'])['awareness'].transform('mean'),inplace=True) ## Replacing with group mean\n",
data['attitude'].fillna(data.groupby(['usage','sex'])['attitude'].transform('mean'),inplace=True)
data['preference'].fillna(data.groupby(['usage','sex'])['preference'].transform('mean'),inplace=True)
data['intention'].fillna(data.groupby(['usage','sex'])['intention'].transform('mean'),inplace=True)
data['loyalty'].fillna(data.groupby(['usage','sex'])['loyalty'].transform('mean'),inplace=True)

In [6]:
data

,Customer_number,usage,sex,awareness,attitude,preference,intention,loyalty,income
0,1,Heavy,Male,7.000000,6.00,5.00,5.00,6.0,95000
1,2,Light,Female,2.000000,2.00,4.00,6.00,5.0,60890
2,3,Light,Female,3.000000,3.00,6.00,7.00,6.0,50998
3,4,Heavy,Male,6.000000,5.00,5.00,3.00,2.0,79103
4,5,Heavy,Male,5.000000,4.00,7.00,4.00,3.0,74216
5,6,Medium,Male,4.000000,3.00,5.00,2.00,3.0,31058
6,7,Medium,Female,5.000000,4.00,4.00,3.00,2.0,24291
7,8,Light,Female,2.000000,1.00,3.00,4.00,5.0,56189
8,9,Medium,Male,4.000000,4.00,3.00,6.00,5.0,31860
9,10,Light,Female,3.000000,1.00,2.00,4.00,5.0,56075
10,11,Heavy,Male,6.000000,7.00,6.00,4.00,5.0,77951
11,12,Heavy,Male,6.000000,5.00,6.00,4.00,4.0,78718
12,13,Light,Female,4.000000,3.00,3.00,1.00,1.0,51668
13,14,Heavy,Male,6.000000,4.00,5.00,3.00,2.0,55936
14,15,Light,Male,4.000000,3.00,4.00,5.00,6.0,56309
15,16,Light,Male,3.000000,4.00,2.00,4.00,2.0,54319
16,17,Heavy,Female,7.000000,6.00,4.00,5.00,3.0,70087
17,18,Medium,Female,6.000000,5.00,4.00,3.00,2.0,37434
18,19,Light,Female,1.000000,1.00,3.00,4.00,5.0,59689
19,20,Heavy,Female,5.000000,7.00,4.00,1.00,2.0,65861
20,21,Heavy,Male,6.000000,6.00,7.00,7.00,5.0,72828
21,22,Medium,Male,2.000000,3.00,1.00,4.00,2.0,42000
22,23,Light,Female,1.000000,1.00,3.00,2.00,2.0,55523
23,24,Heavy,Female,6.000000,7.00,6.00,7.00,6.0,78178
24,25,Light,Male,3.000000,2.00,2.00,1.00,1.0,53595
25,26,Medium,Male,5.000000,3.00,4.00,4.00,5.0,35558
26,27,Heavy,Male,7.000000,6.00,6.00,5.00,7.0,84357
27,28,Medium,Female,6.000000,4.00,2.00,5.00,6.0,30420
28,29,Light,Female,2.230769,2.00,3.00,1.00,3.0,52787
29,30,Medium,Male,5.000000,3.25,4.00,6.00,5.0,41000
30,31,Light,Male,1.000000,2.00,3.25,3.00,2.0,72000
31,32,Light,Male,4.000000,6.00,5.00,3.25,3.0,63882
32,33,Medium,Female,3.000000,4.00,3.00,2.00,4.0,31104
33,34,Medium,Female,4.000000,6.00,5.00,7.00,6.0,43000
34,35,Heavy,Female,5.000000,7.00,7.00,3.00,3.0,75081
35,36,Heavy,Female,6.000000,5.00,7.00,3.00,4.0,71775
36,37,Heavy,Male,6.000000,7.00,5.00,3.00,4.0,73620
37,38,Heavy,Male,5.000000,6.00,4.00,3.00,2.0,66291
38,39,Heavy,Male,7.000000,7.00,6.00,3.00,4.0,63410
39,40,Light,Female,4.000000,3.00,4.00,6.00,5.0,55116
40,41,Light,Female,2.000000,3.00,4.00,5.00,6.0,65680
41,42,Light,Female,1.000000,3.00,2.00,3.00,4.0,47713
42,43,Light,Female,2.000000,4.00,3.00,6.00,7.0,50896
43,44,Light,Female,3.000000,3.00,4.00,6.00,5.0,63848
44,45,Light,Female,1.000000,1.00,4.00,5.00,3.0,52704

In [7]:
data.head()

,Customer_number,usage,sex,awareness,attitude,preference,intention,loyalty,income
0,1,Heavy,Male,7.0,6.0,5.0,5.0,6.0,95000
1,2,Light,Female,2.0,2.0,4.0,6.0,5.0,60890
2,3,Light,Female,3.0,3.0,6.0,7.0,6.0,50998
3,4,Heavy,Male,6.0,5.0,5.0,3.0,2.0,79103
4,5,Heavy,Male,5.0,4.0,7.0,4.0,3.0,74216

###### Q 1. Is there a difference in usage level between male and female customers?
##### Answer: We will use Chi-square test to find this answer. The Chi-Square Test of Independence determines whether there is an association between categorical variables (i.e., whether the variables are independent or related).

##### Hnull: There is no association between two categorical variables
##### H Alt: Both the categorial variables are associated with other

###### It also gives us cramer'V coeffcient , which is measure of level of association between two variables. It is between 0 and 1. Values closer to 1 indicates higher association between the variables.
    
##### In the following example, p-value is 0.04, which is less than 0.05. It indicates that there is not sufficient evidence for not rejecting the null hypothesis. So, we will reject the null hypothesis. We can conclude that there is different level of usage among male and female customers.

In [8]:
crosstab, test_results, expected = rp.crosstab(data["sex"], data["usage"],
                                               test="chi-square",
                                               expected_freqs= True,
                                               prop= "cell")

print(test_results)

                Chi-square test  results
0  Pearson Chi-square ( 2.0) =    6.3413
1                    p-value =    0.0420
2                 Cramer's V =    0.3754

In [10]:
p=test_results['results'][1]
alpha = 0.05

print("H0: both the nominal varibales are not associated with each other")
if p > alpha:
    print('Result: These two nominal variables are not associated (fail to reject H0)')
else:
    print('Result: These two nominal variables are associated (reject H0)')

H0: both the nominal varibales are not associated with each other
Result: These two nominal variables are associated (reject H0)

##### Check if there is correlation between awareness and intention. Use Pearson coefificent if variable is numeric, otherwise for ordinal or rank based variable, you may use spearman or kendall tau correlation"

In [11]:
from scipy.stats import pearsonr
corr, p = pearsonr(data['awareness'], data['intention'])
print(corr,p)

0.07207423821611317 0.6380007280776383

In [13]:
from scipy.stats import spearmanr
corr, p = spearmanr(data['awareness'], data['intention'])
print(corr,p)

0.04390232631865409 0.7746051789230424

In [14]:
from scipy.stats import kendalltau
corr, p = kendalltau(data['awareness'], data['intention'])
print(corr,p)

0.042106674369289256 0.7166288700314304

###### Q. 2 Does awareness of Nike products exceed 3? 

###### Asnwer: We will use one-sample t-test to test this hypothesis. The One Sample t Test determines whether the sample mean is statistically different from a known or hypothesized population mean. We will use one sample t-test to examine if mean of awareness of Nike is different from 3. 

###### Hnull : The mean of awareness among cusotmers is equal to 3.
###### H Alt: The mean of awareness among customers of nike is either greater than 3 or less than 3. 

###### We will run the one sample t-test using the code in following blocks. First, we will check the p-value. Here, p-value is 0.0002 which is less than 0.05. We will reject the Hnull and conclude that awareness is not equal to 3. Mean of awareness for sample is 4.13, which is higher than 3. We can conclude that awareness among nike cusotmers is higher than 3 by 1.13.  Further, positive t-value also indicatges that mean of awareness is higher than 3.

In [15]:
from scipy import stats  ### import the package for conducting t-test analysis"

In [16]:
## First check the average value of awareness
data['awareness'].mean()

4.138461538461538

In [17]:
#One sample t-test
stats.ttest_1samp(data['awareness'], 4)

Ttest_1sampResult(statistic=0.4928644313417907, pvalue=0.6245591359477978)

###### Q.3 Do males and females differ in their awareness for Nike? Their attitude and loyalty toward Nike?

###### Answer: We will conduct independent sample t-test analysis for comparing if awareness is different among male and female customers. The Independent Samples t Test compares the means of two independent groups in order to determine whether there is statistical evidence that the associated population means are significantly different. Here, we assume male and female to be two independent groups. We will check if mean of awareness for male and female are different or not in population.

###### Hnull : The mean of awareness is same among male and female customers.

###### H Alt: Male and female differ in awareness. 


###### To run the analysis, first we will select the awareness values for male and female customers in Awareness_Male and Awareness_Female list. Using these two lists, we will run the independent analysis. p-value of the test is 0.01 , which is less than 0.05. Hence we will reject he null hypothesis and conclude that awareness is different for male and female customers.  To check which group is having higher awareness, we will compute the difference of mean awareness for both the groups. Difference between average awareness for male and female is 1.34, which indicates that awareness is higher among male than female by 1.34.

###### By repeating the same process, you can also check if male and female also differ in their attitude and loyalty for nike.

In [18]:
data.groupby(['sex'])['loyalty'].mean()

sex
Female    4.166667
Male      3.714286
Name: loyalty, dtype: float64

In [19]:
# Independent sample t-test\n",
Awareness_male = data[data['sex'] == 'Male']['attitude']
Awareness_Female = data[data['sex'] == 'Female']['attitude']
stats.ttest_ind(Awareness_male, Awareness_Female)

Ttest_indResult(statistic=1.8146601480694533, pvalue=0.07655613084415247)

In [20]:
Mean_Diff=Awareness_male.mean()-Awareness_Female.mean()
Mean_Diff

0.9999999999999996

###### Q 4.Assume that awareness toward Nike was measured on an ordinal scale rather than an interval scale. Do males and females differ in their awareness towards Nike?

###### Answer: As awareness is measured on ordinal scale now. so we can not apply independent sample t-test. It assumes the variable to be numeric. We will conduct Mann Whitney U test to compare if male and females differs in their awareness for nike.

###### Hnull:Both male and female have equal ranking for awareness 
###### H Alt: Male and female differ in their ranking with respect to awareness. 

###### In the following example, we find a p-value of 0.009. It is less than 0.05. Hence, we will reject the null hypothsis and conclude that male and female differ in their level of awareness.

###### To further check if , male have higher awareness level than female customers, we will run the mann whitney test againg with one more parameter alaternative=\"greater\". P-value less than 0.05 indicates that male has higher awareness than female cusotmers.

In [21]:
## Non-Parametric Independent sample test-- Mann-Whitney U test
stats.mannwhitneyu(Awareness_male,Awareness_Female)

MannwhitneyuResult(statistic=328.5, pvalue=0.07992583133735567)

In [22]:
stats.mannwhitneyu(Awareness_Female,Awareness_male,alternative='less')

# H null: Male and female have equal wareness.
# H alt: Male have higher awareness than female customers.

## you can also pass alternative= \"less\" for checking if male customers have lower awareness than female customers.

MannwhitneyuResult(statistic=175.5, pvalue=0.03996291566867784)

###### Q 5. Do the respondents have higher level of awareness than loyalty?
###### Answer: We need find if each customer has higher level of awareness than loyalty. We will use paired sample t-test to find answer to this question. The paired sample t-test, sometimes called the dependent sample t-test, is a statistical procedure used to determine whether the mean difference between two sets of observations is zero. In a paired sample t-test, each subject or entity is measured twice, resulting in pairs of observations.

###### Hnull: Mean of awarenss and loyalty are same among customer
###### H Alt: Mean of awareness and loyalty are different among customer.

###### We run the paired-sample t-test. P-value for test is 0.77, which is higher than 0.05. Hence, there is sufficient evidence for not rejecting the null hypothesis. Hence, we can conclude that awareness and loyalty are same for all the customers. We can also check the mean value of awareness and preference for all the customers. We can see that mean of awareness is 4.13, while mean for preference is 4.20. Thus, sample data suggests  that preferecne level are slightly higher, but it is not statistically significant and will not hold true for population."

In [23]:
## Paired Sample t-test
stats.ttest_rel(data['awareness'], data['preference'])

Ttest_relResult(statistic=-0.29072990972157675, pvalue=0.7726238964298249)

In [24]:
print(data['awareness'].mean())
print(data['preference'].mean())

4.138461538461538
4.205555555555556

##### Q. 6 Assume that awareness and loyalty were measure on ordinal scale rather than an interval scale. Do the respondents have higher awareness for Nike than loyalty for Nike?

##### Answer: We will use wilcoxon singed rank t-test. The Wilcoxon signed-rank test is a non-parametric statistical hypothesis test used to compare two related samples, matched samples, or repeated measurements on a single sample to assess whether their population mean ranks differ (i.e. it is a paired difference test). 

###### Hnull: Rank of awareness and loyalty are same among customers.
###### H Alt: Rank of awareness is higher than that of loyalty for nike.

##### to Check if level of awareness is greater than level of preferecne, we can put alternative=\"greater\" argument in function. To check if awareness is lesser than preference, we can put  alternative=\"less\". To check if both are different, we can put alternative=\"two-sided\". Default option is \"two-sided\". 

##### we can find that p-value is 0.66, which is greater that 0.05. Hence, we will not reject the null hypothesis. We will conclude that customers do not differ in their awareness and preference for nike.

In [25]:
## Non-Parametric wilxcon paired t-test--Wilcoxon Signed Rank Test
stats.wilcoxon(data['awareness'], data['preference'],alternative='greater')

WilcoxonResult(statistic=361.0, pvalue=0.6622539981200868)

###### Q. 7 Do the various types of customers in terms of usage differ in their awareness for Nike? Their attitude for Nike? Their loyalty for Nike?
###### Answer: Usage level has three groups heavy, medium, and light. As it has more than two groups, we can not apply independent sample t-test to check the group differences. We will conduct one-way analysis of variance (ANOVA) in Python

###### Hnull: There is no difference in mean value of awareness across heavy, medium, and light users.
###### H alt:  Mean of awareness is different across the heavy, medium, and light users.

###### First, we can run group by command to find the average score of awareness for heavy, light, and medium users. We can see that awareness mean is different for these three groups. We will run anova analysis in python. Getting p-value less than 0.05 indicates that mean of awareness of different across heavy, light, and medium usage customers.

###### To compare the mean difference among different pairs of usage level, we can use tukey's post hoc analysis. Let us interpret the results. First line represnts the difference between light and heavy group. Mean diff is -3.41 with p-value = 0.001. As p value is less than 0.05, we conclude that mean awareness for heavy and light users are significant different and mean awareness of heavy users is 3.41 higher than that of light users. 

###### To check the difference in attitude and loyalty among various usage level customers, please run the same analysis for attitude and loyalty variable as well.

In [26]:
data.groupby(['usage'])['awareness'].mean()

usage
Heavy     6.000000
Light     2.433198
Medium    4.400000
Name: awareness, dtype: float64

In [28]:
# stats f_oneway functions takes the groups as input and returns F and P-value
Attribute = 'awareness'
X1=data.loc[data["usage"]=='Heavy',Attribute]
X2=data.loc[data["usage"]=='Medium',Attribute]
X3=data.loc[data["usage"]=='Light',Attribute]
fvalue, pvalue = stats.f_oneway(X1,X2,X3)
print(fvalue, pvalue)

52.10725822565609 4.201794027012068e-12

In [29]:
## for conducting tukey's post hoc analysis.
from statsmodels.stats.multicomp import pairwise_tukeyhsd
m_comp = pairwise_tukeyhsd(endog=data['attitude'], groups=data['usage'], alpha=0.05)
print(m_comp)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
 Heavy  Light  -3.4112  0.001 -4.3646 -2.4578   True
 Heavy Medium  -2.0125  0.001 -3.1451 -0.8799   True
 Light Medium   1.3987 0.0096   0.301  2.4964   True
----------------------------------------------------